name: Crowdin Action

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - develop
  schedule:
    - cron: "0 */12 * * *"

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: rickycodes/github-action@deb06592ad2a702b7e4157d7604e0addbffdac0a
      with:
        upload_translations: true
        download_translations: true
      env:
        GITHUB_TOKEN: ${{ secrets.METAMASKBOT_CROWDIN_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
